# Generated by Django 5.2.9 on 2026-01-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('data', 'Data & AI'), ('marketing', 'Marketing'), ('design', 'Design'), ('hr', 'HR')], default='engineering', max_length=50),
        ),
    ]
